### ISSUE TITLE
Markdown links and images aren't rendered

### ISSUE THREAD

**Issue by logseqramses** [scripting/myLogseqBlog#3]
I had expected that I could use Markdown links, but neither text links nor images render:
http://oldschool.scripting.com/rroudt/2022/01/12/000003.html?title=writingABlogInAnOutline

<img width="670" alt="CleanShot 2022-01-14 at 00 22 30@2x" src="https://user-images.githubusercontent.com/96059866/149424358-a6deaf06-8ced-40ac-ad04-ec93fc05f79b.png">

**Comment by scripting** [comment]
@logseqramses -- thanks for the report, I updated the software so now it understands Markdown syntax when it's rendering the blog.

@andrewshell -- I noticed you were using Markdown on your blog, it should work now. 

Here's my [blog post](http://oldschool.scripting.com/mylogseqblog/2022/01/13/000005.html?title=changeNotesForV041) on this update.

**Comment by Hileotech** [comment]
HI! First of all thanks for your work!
I still can't figure out how to see images, even after your fix.
If you follow Ramses link (as I did few minutes ago), you can see no image is displayed after "Here's how it looks like in Logseq:"
I succesfully "installed" your script and published my Drummer here: http://oldschool.scripting.com/profmacrobio/2022/01/14.html 
No image (i took one from Wikipedia, this one to be precise: https://en.wikipedia.org/wiki/Library_of_Trinity_College_Dublin#/media/File:Long_Room_Interior,_Trinity_College_Dublin,_Ireland_-_Diliff.jpg) uploaded from /assets folder, as you can see in my screenshot:

<img width="691" alt="Schermata 2022-01-14 alle 17 06 53" src="https://user-images.githubusercontent.com/81426495/149547129-ec3ee2bd-df64-41e1-936b-01464eedabbd.png">


Am I doing something wrong? I had no error in Terminal when running the script

Thanks

**Comment by scripting** [comment]
Hi @Hileotech -- I re-read your comment, now I see you're reporting a problem with _your_ blog. Investigating...

**Comment by Hileotech** [comment]
Hi @scripting !

Thanks: that's what I meant...

**Comment by scripting** [comment]
@Hileotech -- I see a problem, it may not be the only one, but the URL of the image has to be fully specified. 

../assets/trinity-college-library_1642168711998_0.jpg

Try entering that into a web browser. It won't find it. 

It has to be something like http://trinity.edu/assets/trinity-college-library_1642168711998_0.jpg

**Comment by Hileotech** [comment]
I thought about this, thanks for confirming.
This means that when I write for the blog I can't embed "local" (./assets) files, but I have to link them from the web.
What if I wanted to publish a photo/image of mine? Should I rely on some service or do you think you could implement this function?

Again, thank you for your work!

EDIT: forgot to mention: it works using URLs

**Comment by scripting** [comment]
That's a question to ask a bit down the road. We're just getting started here. ;-)
